version: '3'

services:
  web:
    build: .
    volumes:
      - ./data:/data
      - cwb-parallel-volume:/cwb
    restart: always
    env_file:
      - web-variables.env
    container_name: cwb-parallel
    ports:
     - "8003:8000"

volumes:
  cwb-parallel-volume:
