version: "3.9"
services:
    # cwb:
    #     build: .
    #     container_name: "cwb"
    #     volumes:
    #         - registry-vol:/app/cwb/registry
    #         - data-vol:/app/cwb/data
    #         - tmp-vol:/app/cwb/tmp
    #         - uploads-vol:/app/cwb/uploads
    #         - cwb-vol:/usr/local/cwb-3.4.22/bin
    #     tty: true
    cqpweb:
        build: .
        container_name: "cqpweb"
        ports: 
            - "8004:80"
        volumes:
            - cwb-vol:/cwb
            - cqpweb-vol:/usr/local/apache2/htdocs/
            # - uploads-vol:/app/cwb/uploads
            - ./conf/my-httpd.conf:/usr/local/apache2/conf/httpd.conf
            - ./conf/php.ini:/etc/php/7.4/apache2/php.ini
            - ./data/uploads:/cwb/uploads
        depends_on: 
            - mysql

    mysql:
        container_name: "mysql"
        image: mysql:8.0
        env_file:
            - ./conf/mysql.conf.env
        volumes:
            - mysql-vol:/var/lib/mysql
            - ./conf/my.cnf:/etc/mysql/my.cnf
        expose:
            - "3306"
        command:  ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
volumes:
    cwb-vol:
    mysql-vol:
    cqpweb-vol:
    
