version: "3.9"
services:
    cwb:
        build: .
        container_name: "cwb"
        volumes:
            - registry-vol:/app/cwb/registry
            - data-vol:/app/cwb/data
            - tmp-vol:/app/cwb/tmp
            - uploads-vol:/app/cwb/uploads
            - cwb-vol:/usr/local/cwb-3.4.22/bin
        tty: true
    php-apache:
        build:
            context: .
            dockerfile: Dockerfile-apache
        container_name: "cqpweb"
        ports: 
            - "5000:80"
        volumes:
            - registry-vol:/app/cwb/registry
            - data-vol:/app/cwb/data
            - tmp-vol:/app/cwb/tmp
            - uploads-vol:/app/cwb/uploads
            - cwb-vol:/usr/local/cwb-3.4.22/bin
        depends_on: 
            - mysql

    mysql:
        container_name: "mysql"
        image: mysql:8.0
        env_file:
            - ./conf/mysql.conf.env
        volumes:
            - mysql-vol:/var/lib/mysql
        # ports:
        #     - "3306:3306"
        expose:
            - "3306"
        command:  ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
volumes:
    registry-vol:
    data-vol:
    tmp-vol:
    uploads-vol:
    cwb-vol:
    mysql-vol:
    
